### ISSUE TITLE
Using Item Search Function near Betweenlands TEs throws NPE

### ISSUE THREAD

**Issue by SargeRyong** [Buuz135/FindMe#2]
To reproduce: 

- Place a TileEntity from Betweenlands that has an inventory (e.g., a Purifier) near a chest, and place an item in the chest.
-  Search for said item. 
- Observe that inventory does not close and smoke particles are not emitted and that a NullPointerException has been caught and logged.  
- Move away from or remove the Betweenlands block and repeat the search.  
- Observe that the item seearch function works as expected. 

I can confirm this is reproducible with the Purifier and Sulfur Furnace - probably with every inventory that isn't the Weedwood chest.   

Here's the stack trace: 

[Server thread/FATAL] [net.minecraft.server.MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_171]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_171]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]

**Comment by Buuz135** [comment]
Thats an Betweenlands issue. When I request if the tiles have the `ITEM_HANDLER_CAPABILITY` on the `null` side it returns `true` but when I get the capability I get a `null` one.

**Comment by Walkman100** [comment]
Sounds like the same issue I'm facing (MC 1.12.2, findme 1.1.0-8 in SevTech Ages v3.2.1), the server spits this out if it finds an item:
```
[20:08:55] [Server thread/FATAL] [minecraft/MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_311]
        at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_311]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_311]
Caused by: java.lang.NullPointerException
        at micdoodle8.mods.galacticraft.core.tile.TileEntityInventory.func_191420_l(TileEntityInventory.java:46) ~[TileEntityInventory.class:?]
        at com.buuz135.findme.network.PositionRequestMessage$Handler.lambda$onMessage$0(PositionRequestMessage.java:85) ~[PositionRequestMessage$Handler.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_311]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_311]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 5 more
```
