### ISSUE TITLE
Doesn't work on Fabric servers

### ISSUE THREAD

**Issue by Frogperson** [Buuz135/FindMe#44]
```
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'findme' at 'com.buuz135.findme.fabric.FindMeFabric'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403) ~[fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401) ~[fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.16.2.jar:?]
	at net.minecraft.server.Main.main(Main.java:111) [server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.16.2.jar:?]
Caused by: java.lang.AbstractMethodError: Receiver class dev.architectury.networking.fabric.NetworkManagerImpl$1 does not define or inherit an implementation of the resolved method 'abstract void registerS2C(net.minecraft.class_8710$class_9154, net.minecraft.class_9139, dev.architectury.networking.NetworkManager$NetworkReceiver)' of interface dev.architectury.impl.NetworkAggregator$Adaptor.
	at dev.architectury.impl.NetworkAggregator.registerS2CReceiver(NetworkAggregator.java:119) ~[architectury-13.0.3-fabric.jar:?]
	at dev.architectury.impl.NetworkAggregator.registerReceiver(NetworkAggregator.java:91) ~[architectury-13.0.3-fabric.jar:?]
	at dev.architectury.networking.NetworkManager.registerReceiver(NetworkManager.java:102) ~[architectury-13.0.3-fabric.jar:?]
	at dev.architectury.networking.NetworkManager.registerReceiver(NetworkManager.java:97) ~[architectury-13.0.3-fabric.jar:?]
	at com.buuz135.findme.FindMeMod.init(FindMeMod.java:45) ~[findme-3.3.1-fabric.jar:?]
	at com.buuz135.findme.fabric.FindMeFabric.onInitialize(FindMeFabric.java:24) ~[findme-3.3.1-fabric.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.2.jar:?]
	... 6 more
```

Seems to be this maybe?
> `S2C` packets need to be registered differently on clients and servers:
> On clients, you call `registerReceiver` and on servers you call `registerS2CPayloadType`.
https://github.com/architectury/architectury-api/issues/518#issuecomment-2189789212

**Comment by Dragon911XX** [comment]
I'm still having this issue on 1.21.1 both with 3.3.1 and 3.3.2 of FindMe. Only other mod is Architectury 13.0.8.
